"""Add created_at field to bets table

Revision ID: 19c7d9d0f37e
Revises: 
Create Date: 2025-10-22 08:43:20.543474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c7d9d0f37e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column('bets', sa.Column('created_at', sa.DateTime(), nullable=True))
    
    # Update existing rows with current timestamp
    op.execute("UPDATE bets SET created_at = datetime('now') WHERE created_at IS NULL")
    
    op.create_index(op.f('ix_bets_backroll_id'), 'bets', ['backroll_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bets_backroll_id'), table_name='bets')
    op.drop_column('bets', 'created_at')
    op.alter_column('backroll', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
